wip: ltp: upgrade 20190517 -> 20190930
These patches have been merged upstream:
* 0010-shmctl01-don-t-use-hardcoded-index-0-for-SHM_STAT-te.patch \
* 0011-direct_io-diotest4-drop-MAP_FIXED.patch \
* 0012-getrlimit03-adjust-a-bit-of-code-to-compatiable-with.patch \
* 0001-Add-configure-time-check-for-getdents-getdents64-API.patch \
* 0001-syscalls-tgkill03-wait-for-defunct-tid-to-get-detach.patch \
* 0001-ustat02-Fix-EFAULT-in-32bit-compatibility-mode.patch \
* 0001-cve-meltdown.c-Fix-kernel-symbol-finding.patch \
* 0001-testcases-use-python3-everywhere-to-run-python-scrip.patch \
* 0001-syscall-rt_sigtimedwait01-Fix-wrong-sigset-length-fo.patch \
* 0001-cve-2017-17052-Avoid-unsafe-exits-in-threads.patch \

This patch is no longer required:
* 0002-check-for-RES_USE_INET6-during-configure.patch \

Remaining patches have been refreshed.

Package net-tools has been added as a run-time dependency as
containers/netns requires a real ipconfig, not the one shipped
with Busybox.

These tests still fail with MUSL:
* testcases/kernel/syscalls/timer_create/timer_create01.c
* testcases/kernel/syscalls/timer_create/timer_create03.c
because:
| timer_create01.c:41:12: error: 'SIGEV_THREAD_ID' undeclared here (not in a function); did you mean 'SIGEV_THREAD'?
and:
| timer_create03.c:40:5: error: 'struct sigevent' has no member named '_sigev_un'

Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>